"""
recon.modules.http_probe — Deep HTTP/HTTPS fingerprinting and web reconnaissance.

Capabilities:
- WAF detection (22 WAF signatures: Cloudflare, ModSecurity, Akamai, F5, Imperva, …)
- CDN detection (14 providers: Cloudflare, CloudFront, Fastly, Akamai, Varnish, …)
- Technology stack fingerprinting (65+ technologies: CMS, frameworks, servers, JS libs)
- Security header audit with severity scoring (HSTS, CSP, X-Frame-Options, …)
- Sensitive path/admin panel/API endpoint discovery
- Cookie security analysis (HttpOnly, Secure, SameSite flags)
- HTTP method enumeration (OPTIONS, PUT, DELETE, TRACE, PATCH)
- Redirect chain following
- robots.txt / sitemap.xml harvesting
- Server-side software version disclosure detection
"""

from __future__ import annotations

import http.client
import json
import re
import socket
import ssl
import threading
import time
import urllib.parse
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Any

from recon.core.config import ReconConfig
from recon.core.logger import get_logger, make_progress

__all__ = ["HTTPProbe", "WebFingerprint"]

_log = get_logger("http_probe")

# ──────────────────────────────────────────────────────────────────────────────
# Signature databases
# ──────────────────────────────────────────────────────────────────────────────

_WAF_SIGNATURES: dict[str, dict[str, list[str]]] = {
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-request-id", "cf-connecting-ip"],
        "server":   ["cloudflare"],
        "cookies":  ["__cflb", "__cf_bm", "cf_clearance"],
        "body":     ["Attention Required! | Cloudflare", "cloudflare-nginx",
                     "DDoS protection by Cloudflare"],
    },
    "AWS WAF": {
        "headers":  ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "body":     ["<title>403 Forbidden</title>", "Request blocked"],
    },
    "ModSecurity": {
        "headers":  ["x-powered-by-modsecurity"],
        "body":     ["Mod_Security", "mod_security", "NOYB",
                     "Not Acceptable!"],
    },
    "Akamai Kona": {
        "headers":  ["akamai-origin-hop", "x-check-cacheable",
                     "x-akamai-transformed", "x-akamai-ssl-client-sid"],
        "server":   ["AkamaiGHost", "AkamaiNetStorage"],
    },
    "F5 BIG-IP ASM": {
        "cookies":  ["BIGipServer", "BigIP", "F5_HT_shrinked", "F5_fullWT"],
        "headers":  ["x-cnection", "x-wa-info"],
        "body":     ["The requested URL was rejected"],
    },
    "Imperva Incapsula": {
        "cookies":  ["incap_ses", "visid_incap", "_incap_"],
        "headers":  ["x-iinfo", "x-cdn"],
        "body":     ["incapsula incident id"],
    },
    "Barracuda WAF": {
        "cookies":  ["barra_counter_session"],
        "body":     ["barracuda_", "barracuda networks"],
    },
    "Sucuri CloudProxy": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "server":   ["Sucuri/Cloudproxy"],
        "body":     ["Access Denied - Sucuri Website Firewall"],
    },
    "Fortinet FortiGate": {
        "cookies":  ["FORTIWAFSID"],
        "body":     ["FortiGate", "FortiWeb"],
    },
    "Citrix NetScaler ADC": {
        "headers":  ["ns_af", "x-nsprotect"],
        "cookies":  ["citrix_ns_id", "NSC_"],
    },
    "Wallarm": {
        "headers":  ["wallarm-debug"],
        "body":     ["Wallarm"],
    },
    "PerimeterX": {
        "cookies":  ["_px", "_pxde", "_pxhd"],
        "body":     ["px-captcha", "PerimeterX"],
    },
    "DataDome": {
        "cookies":  ["datadome"],
        "headers":  ["x-datadome-cid"],
    },
    "Radware AppWall": {
        "cookies":  ["PLBSID"],
        "body":     ["Unauthorized Activity Has Been Detected",
                     "Radware"],
    },
    "DDoS-Guard": {
        "cookies":  ["__ddg1", "__ddg2", "__ddgid"],
        "server":   ["ddos-guard"],
    },
    "Wordfence": {
        "body":     ["generated by Wordfence", "This site is protected by Wordfence"],
    },
    "SiteLock": {
        "headers":  ["x-sitelock-request-id"],
    },
    "Reblaze": {
        "cookies":  ["rbzid"],
        "headers":  ["x-reblaze-protection"],
    },
    "Alibaba Cloud WAF": {
        "headers":  ["ali-cdn", "x-swift-savetime"],
        "body":     ["Alibaba Cloud"],
    },
    "Tencent Cloud WAF": {
        "headers":  ["x-cache-lookup"],
        "body":     ["Tencent WAF"],
    },
    "Huawei WAF": {
        "body":     ["Huawei Cloud WAF"],
    },
    "Cloudflare Bot Mgmt": {
        "cookies":  ["__cfruid"],
        "headers":  ["cf-mitigated"],
    },
}

_CDN_SIGNATURES: dict[str, dict[str, list[str]]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status"],
        "server":  ["cloudflare"],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-origin-hop",
                    "x-akamai-transformed", "x-true-cache-key"],
        "server":  ["AkamaiGHost", "AkamaiNetStorage"],
    },
    "Amazon CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "server":  ["CloudFront"],
        "via":     ["CloudFront"],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-cache-hits", "fastly-restarts",
                    "x-fastly-request-id"],
        "via":     ["varnish"],
    },
    "Varnish": {
        "headers": ["x-varnish", "x-grace"],
        "via":     ["varnish"],
    },
    "Azure CDN": {
        "headers": ["x-ec-custom-error", "x-azure-ref", "x-ms-ref"],
    },
    "Google Cloud CDN": {
        "headers": ["x-goog-generation"],
        "server":  ["gws", "sffe", "ESF"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
    },
    "MaxCDN / StackPath": {
        "headers": ["x-hw", "x-pull-zone-id"],
    },
    "KeyCDN": {
        "headers": ["x-edge-location", "x-edge-ip"],
    },
    "BunnyCDN": {
        "headers": ["cdn-pullzone", "cdn-uid"],
    },
    "jsDelivr": {
        "headers": ["x-jsdelivr-version"],
    },
    "Imperva": {
        "headers": ["x-iinfo"],
    },
    "Limelight / Edgio": {
        "headers": ["x-check-cacheable", "x-ll-sid"],
    },
}

_TECH_SIGNATURES: dict[str, dict[str, list[str]]] = {
    # ── CMS ───────────────────────────────────────────────────────────────────
    "WordPress": {
        "headers": ["x-pingback"],
        "paths":   ["/wp-content/", "/wp-admin/", "/wp-includes/"],
        "meta":    [r'<meta name="generator" content="WordPress'],
        "cookies": ["wordpress_", "wp-settings-"],
        "body":    ["/wp-content/", "wp-json"],
    },
    "Drupal": {
        "headers": ["x-drupal-cache", "x-drupal-dynamic-cache", "x-generator"],
        "paths":   ["/sites/default/", "/modules/", "/themes/"],
        "meta":    [r'<meta name="Generator" content="Drupal'],
        "body":    ["Drupal.settings"],
    },
    "Joomla": {
        "paths":   ["/components/com_", "/administrator/"],
        "meta":    [r'<meta name="generator" content="Joomla'],
        "body":    ["Joomla!"],
    },
    "Magento": {
        "cookies": ["form_key", "frontend"],
        "paths":   ["/skin/frontend/", "/app/design/"],
        "body":    ["Mage.Cookies", "varien"],
    },
    "Shopify": {
        "headers": ["x-shopify-stage", "x-shopify-shop-api-call-limit"],
        "body":    ["cdn.shopify.com", "Shopify.theme"],
    },
    "OpenCart": {
        "body":    ["route=common/home", "catalog/view/theme"],
    },
    "PrestaShop": {
        "cookies": ["PrestaShop-"],
        "meta":    [r'<meta name="generator" content="PrestaShop'],
    },
    "TYPO3": {
        "body":    ["typo3/", "TYPO3"],
        "meta":    [r'<meta name="generator" content="TYPO3'],
    },
    "Wix": {
        "headers": ["x-wix-rendered-pages-timeout"],
        "body":    ["wixsite.com", "wix-thunderbolt", "parastorage.com"],
    },
    "Squarespace": {
        "body":    ["static1.squarespace.com", "squarespace-cdn"],
    },
    # ── Frameworks ────────────────────────────────────────────────────────────
    "Django": {
        "cookies":     ["csrftoken", "sessionid"],
        "body":        ["csrfmiddlewaretoken"],
    },
    "Ruby on Rails": {
        "headers":     ["x-runtime", "x-request-id"],
        "cookies":     ["_session_id", "_rails_session"],
        "powered_by":  ["Phusion Passenger"],
    },
    "Laravel": {
        "cookies":     ["laravel_session", "XSRF-TOKEN"],
    },
    "ASP.NET": {
        "powered_by":  ["ASP.NET", "ASP.NET MVC"],
        "headers":     ["x-aspnet-version", "x-aspnetmvc-version"],
        "cookies":     ["ASP.NET_SessionId", "__RequestVerificationToken"],
    },
    "Express.js": {
        "powered_by":  ["Express"],
    },
    "Next.js": {
        "headers":     ["x-nextjs-cache", "x-nextjs-page"],
        "powered_by":  ["Next.js"],
    },
    "Nuxt.js": {
        "headers":     ["x-nuxt-render-duration"],
    },
    "Flask": {
        "powered_by":  ["Werkzeug", "Flask"],
        "server":      ["Werkzeug"],
    },
    "FastAPI": {
        "body":        ['"detail":"Not Found"', "FastAPI"],
    },
    "Spring Boot": {
        "paths":       ["/actuator/health", "/actuator"],
        "body":        ['"status":"UP"', "Spring"],
    },
    # ── Servers ───────────────────────────────────────────────────────────────
    "nginx":          {"server": ["nginx"]},
    "Apache":         {"server": ["Apache", "Apache-Coyote"]},
    "Microsoft IIS":  {"server": ["Microsoft-IIS", "IIS"]},
    "LiteSpeed":      {"server": ["LiteSpeed", "OpenLiteSpeed"]},
    "Caddy":          {"server": ["Caddy"]},
    "Gunicorn":       {"server": ["gunicorn"]},
    "Tomcat":         {"server": ["Apache-Coyote", "Tomcat"]},
    "Jetty":          {"server": ["Jetty"]},
    # ── APIs / tooling ────────────────────────────────────────────────────────
    "Swagger / OpenAPI": {
        "paths": ["/swagger-ui.html", "/swagger-ui/", "/api-docs",
                  "/openapi.json", "/v2/api-docs", "/swagger.json"],
    },
    "GraphQL": {
        "paths": ["/graphql", "/api/graphql", "/graphiql"],
        "body":  ['"data":', '"errors":['],
    },
    "Kubernetes API": {
        "paths": ["/api/v1", "/apis/apps/v1", "/healthz"],
    },
    "Grafana": {
        "paths": ["/login", "/api/health"],
        "body":  ["Grafana"],
        "headers": ["x-frame-options"],
    },
    "Jenkins": {
        "paths":   ["/api/json", "/login"],
        "body":    ["Jenkins"],
        "headers": ["x-jenkins", "x-jenkins-session"],
    },
    "Kibana": {
        "paths":   ["/app/kibana", "/api/status"],
        "headers": ["kbn-name", "kbn-version"],
    },
    "Prometheus": {
        "paths": ["/metrics", "/-/healthy"],
        "body":  ["# HELP ", "# TYPE "],
    },
    "Elasticsearch": {
        "paths": ["/", "/_cat/health"],
        "body":  ['"cluster_name"', '"version":{', "You Know, for Search"],
    },
    "MinIO": {
        "server": ["MinIO"],
        "body":   ["MinIO"],
    },
}

_SENSITIVE_PATHS: list[tuple[str, str]] = [
    # Admin panels
    ("/admin",                  "admin panel"),
    ("/admin/",                 "admin panel"),
    ("/administrator",          "admin panel"),
    ("/administrator/",         "admin panel"),
    ("/wp-admin/",              "WordPress admin"),
    ("/phpmyadmin",             "phpMyAdmin DB console"),
    ("/phpmyadmin/",            "phpMyAdmin DB console"),
    ("/pma/",                   "phpMyAdmin DB console"),
    ("/mysql/",                 "MySQL admin"),
    ("/cpanel",                 "cPanel"),
    ("/webmin/",                "Webmin"),
    ("/directadmin/",           "DirectAdmin"),
    # Config / source leakage
    ("/.env",                   "dotenv config (HIGH — may contain secrets)"),
    ("/.env.local",             "dotenv config"),
    ("/.env.production",        "dotenv config"),
    ("/.env.backup",            "dotenv config backup"),
    ("/.git/HEAD",              "git repository exposed"),
    ("/.git/config",            "git config exposed"),
    ("/.svn/entries",           "SVN repo exposed"),
    ("/.DS_Store",              "macOS metadata"),
    ("/web.config",             "IIS config"),
    ("/config.php",             "PHP config"),
    ("/configuration.php",      "Joomla config"),
    ("/wp-config.php.bak",      "WordPress config backup"),
    ("/composer.json",          "Composer manifest"),
    ("/package.json",           "npm manifest"),
    # Backup files
    ("/backup.zip",             "backup archive"),
    ("/backup.tar.gz",          "backup archive"),
    ("/site.zip",               "site archive"),
    ("/db.sql",                 "database dump"),
    ("/database.sql",           "database dump"),
    ("/dump.sql",               "database dump"),
    # API / debugging
    ("/api",                    "API root"),
    ("/api/v1",                 "API v1"),
    ("/api/v2",                 "API v2"),
    ("/swagger-ui.html",        "Swagger UI (API docs)"),
    ("/swagger-ui/",            "Swagger UI (API docs)"),
    ("/openapi.json",           "OpenAPI spec"),
    ("/v2/api-docs",            "Swagger API docs"),
    ("/graphql",                "GraphQL endpoint"),
    ("/graphiql",               "GraphiQL (interactive GraphQL)"),
    # Spring Boot Actuator
    ("/actuator",               "Spring Boot Actuator (HIGH — may leak internals)"),
    ("/actuator/health",        "Actuator health endpoint"),
    ("/actuator/env",           "Actuator env (HIGH — may leak env vars)"),
    ("/actuator/beans",         "Actuator beans"),
    ("/actuator/mappings",      "Actuator URL mappings"),
    ("/actuator/httptrace",     "Actuator HTTP trace"),
    # Disclosure
    ("/robots.txt",             "robots.txt"),
    ("/sitemap.xml",            "sitemap"),
    ("/.well-known/security.txt","security.txt"),
    ("/server-status",          "Apache server-status"),
    ("/server-info",            "Apache server-info"),
    ("/nginx_status",           "nginx status page"),
    ("/metrics",                "Prometheus metrics (may expose internals)"),
    # Auth / misc
    ("/phpinfo.php",            "phpinfo() (HIGH — full config exposure)"),
    ("/info.php",               "phpinfo()"),
    ("/test.php",               "PHP test file"),
    ("/.htaccess",              "Apache htaccess"),
    ("/.htpasswd",              "htpasswd file"),
    ("/crossdomain.xml",        "Flash cross-domain policy"),
    ("/clientaccesspolicy.xml", "Silverlight access policy"),
    ("/trace.axd",              "ASP.NET trace"),
    ("/elmah.axd",              "ELMAH error log"),
]

_SECURITY_HEADERS: dict[str, dict[str, str]] = {
    "strict-transport-security": {
        "severity": "HIGH",
        "miss": "HSTS not set — browsers can be tricked into HTTP downgrade",
        "fix":  "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload",
    },
    "content-security-policy": {
        "severity": "HIGH",
        "miss": "CSP absent — XSS impact is unrestricted",
        "fix":  "Add a Content-Security-Policy header",
    },
    "x-frame-options": {
        "severity": "MEDIUM",
        "miss": "X-Frame-Options absent — clickjacking risk",
        "fix":  "X-Frame-Options: DENY  (or use CSP frame-ancestors)",
    },
    "x-content-type-options": {
        "severity": "LOW",
        "miss": "X-Content-Type-Options absent — MIME-type sniffing enabled",
        "fix":  "X-Content-Type-Options: nosniff",
    },
    "referrer-policy": {
        "severity": "LOW",
        "miss": "Referrer-Policy absent — URL path leakage to third parties",
        "fix":  "Referrer-Policy: strict-origin-when-cross-origin",
    },
    "permissions-policy": {
        "severity": "INFO",
        "miss": "Permissions-Policy absent",
        "fix":  "Add Permissions-Policy to restrict camera/mic/geolocation",
    },
    "cross-origin-resource-policy": {
        "severity": "INFO",
        "miss": "CORP absent",
        "fix":  "Cross-Origin-Resource-Policy: same-origin",
    },
    "cross-origin-opener-policy": {
        "severity": "INFO",
        "miss": "COOP absent",
        "fix":  "Cross-Origin-Opener-Policy: same-origin",
    },
}

_BAD_HEADER_VALUES: dict[str, list[str]] = {
    "x-powered-by":  [],    # any value → version disclosure
    "server":        [],    # version token in value
    "x-aspnet-version": [], # any value
    "x-aspnetmvc-version": [],
}

_HTTP_METHODS = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS",
                 "HEAD", "TRACE", "CONNECT", "PROPFIND", "MOVE"]


# ──────────────────────────────────────────────────────────────────────────────
# Data classes
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class WebFingerprint:
    """Aggregated HTTP fingerprint for a single target."""
    target: str
    port: int
    scheme: str
    status_code: int = 0
    server: str = ""
    waf: str = ""
    cdn: str = ""
    technologies: list[str] = field(default_factory=list)
    security_header_issues: list[dict[str, str]] = field(default_factory=list)
    interesting_paths: list[dict[str, Any]] = field(default_factory=list)
    allowed_methods: list[str] = field(default_factory=list)
    cookies: list[dict[str, Any]] = field(default_factory=list)
    redirect_chain: list[str] = field(default_factory=list)
    robots_entries: list[str] = field(default_factory=list)
    version_disclosures: list[str] = field(default_factory=list)
    all_headers: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "target": self.target,
            "port": self.port,
            "scheme": self.scheme,
            "status_code": self.status_code,
            "server": self.server,
            "waf": self.waf,
            "cdn": self.cdn,
            "technologies": self.technologies,
            "security_header_issues": self.security_header_issues,
            "interesting_paths": self.interesting_paths,
            "allowed_methods": self.allowed_methods,
            "version_disclosures": self.version_disclosures,
        }


# ──────────────────────────────────────────────────────────────────────────────
# Main class
# ──────────────────────────────────────────────────────────────────────────────

class HTTPProbe:
    """
    Deep HTTP/HTTPS fingerprinting and web reconnaissance.

    Args:
        target: Hostname or IP.
        port:   HTTP port (auto-detected if None).
        ssl:    Force HTTPS (auto-detected if None).
        config: ReconConfig instance.
    """

    def __init__(
        self,
        target: str,
        port: int | None = None,
        use_ssl: bool | None = None,
        config: ReconConfig | None = None,
    ) -> None:
        self.target = target
        self.config = config or ReconConfig()
        self._timeout = self.config.timeout

        # Auto-detect scheme / port
        if use_ssl is None:
            use_ssl = (port == 443) if port else False
        if port is None:
            port = 443 if use_ssl else 80
        self.port = port
        self.use_ssl = use_ssl
        self.scheme = "https" if use_ssl else "http"
        self._results: WebFingerprint = WebFingerprint(
            target=target, port=port, scheme=self.scheme
        )

    # ── connection helper ─────────────────────────────────────────────────────

    def _connect(self) -> http.client.HTTPConnection | http.client.HTTPSConnection:
        if self.use_ssl:
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            conn = http.client.HTTPSConnection(
                self.target, self.port, timeout=self._timeout, context=ctx
            )
        else:
            conn = http.client.HTTPConnection(
                self.target, self.port, timeout=self._timeout
            )
        return conn

    def _get(
        self,
        path: str = "/",
        method: str = "GET",
        headers: dict[str, str] | None = None,
        follow_redirects: int = 3,
    ) -> tuple[int, dict[str, str], str]:
        """
        Perform an HTTP request.

        Returns:
            (status_code, headers_dict, body_snippet)
        """
        _headers = {
            "User-Agent": (
                "Mozilla/5.0 (X11; Linux x86_64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            "Accept": "text/html,application/xhtml+xml,application/json,*/*;q=0.9",
            "Accept-Language": "en-US,en;q=0.9",
            "Connection": "close",
        }
        if headers:
            _headers.update(headers)

        for _ in range(follow_redirects + 1):
            try:
                conn = self._connect()
                conn.request(method, path, headers=_headers)
                resp = conn.getresponse()
                status = resp.status
                hdrs = {k.lower(): v for k, v in resp.getheaders()}
                body = resp.read(8192).decode("utf-8", errors="replace")
                conn.close()

                if status in (301, 302, 303, 307, 308) and follow_redirects > 0:
                    location = hdrs.get("location", "")
                    if location:
                        self._results.redirect_chain.append(location)
                        parsed = urllib.parse.urlparse(location)
                        if parsed.netloc and parsed.netloc != self.target:
                            break  # external redirect
                        path = parsed.path or "/"
                        follow_redirects -= 1
                        continue
                return status, hdrs, body
            except Exception:
                return 0, {}, ""
        return 0, {}, ""

    # ── WAF detection ─────────────────────────────────────────────────────────

    def detect_waf(self, status: int, hdrs: dict[str, str], body: str,
                   cookies_str: str) -> str:
        """Return detected WAF name or empty string."""
        hdrs_lower = {k.lower(): v.lower() for k, v in hdrs.items()}
        body_lower = body.lower()
        server = hdrs_lower.get("server", "")
        set_cookie = hdrs_lower.get("set-cookie", "") + " " + cookies_str.lower()

        for waf_name, sig in _WAF_SIGNATURES.items():
            score = 0
            for hdr_key in sig.get("headers", []):
                if hdr_key.lower() in hdrs_lower:
                    score += 2
            for srv in sig.get("server", []):
                if srv.lower() in server:
                    score += 3
            for ck in sig.get("cookies", []):
                if ck.lower() in set_cookie:
                    score += 2
            for b in sig.get("body", []):
                if b.lower() in body_lower:
                    score += 2
            if score >= 2:
                return waf_name
        return ""

    # ── CDN detection ─────────────────────────────────────────────────────────

    def detect_cdn(self, hdrs: dict[str, str]) -> str:
        """Return detected CDN name or empty string."""
        hdrs_lower = {k.lower(): v.lower() for k, v in hdrs.items()}
        server = hdrs_lower.get("server", "")
        via = hdrs_lower.get("via", "")

        for cdn_name, sig in _CDN_SIGNATURES.items():
            for hdr_key in sig.get("headers", []):
                if hdr_key.lower() in hdrs_lower:
                    return cdn_name
            for srv in sig.get("server", []):
                if srv.lower() in server:
                    return cdn_name
            for v in sig.get("via", []):
                if v.lower() in via:
                    return cdn_name
        return ""

    # ── Technology fingerprinting ─────────────────────────────────────────────

    def fingerprint_tech(
        self,
        hdrs: dict[str, str],
        body: str,
        cookies_str: str,
        extra_paths_found: list[str] | None = None,
    ) -> list[str]:
        """Return list of detected technology names."""
        detected: list[str] = []
        hdrs_lower = {k.lower(): v.lower() for k, v in hdrs.items()}
        body_lower = body.lower()
        server = hdrs_lower.get("server", "")
        powered = hdrs_lower.get("x-powered-by", "")
        set_cookie = hdrs_lower.get("set-cookie", "") + " " + cookies_str.lower()
        paths_found = set(extra_paths_found or [])

        for tech_name, sig in _TECH_SIGNATURES.items():
            score = 0
            for hdr_key in sig.get("headers", []):
                k = hdr_key.split(":")[0].lower()
                if k in hdrs_lower:
                    score += 2
            for srv in sig.get("server", []):
                if srv.lower() in server:
                    score += 3
            for pw in sig.get("powered_by", []):
                if pw.lower() in powered:
                    score += 3
            for ck in sig.get("cookies", []):
                if ck.lower() in set_cookie:
                    score += 2
            for p in sig.get("paths", []):
                if p.lower() in body_lower or p in paths_found:
                    score += 1
            for m in sig.get("meta", []):
                if re.search(m, body, re.IGNORECASE):
                    score += 3
            for b in sig.get("body", []):
                if b.lower() in body_lower:
                    score += 1
            if score >= 2:
                detected.append(tech_name)

        return detected

    # ── Security header audit ─────────────────────────────────────────────────

    def audit_security_headers(
        self, hdrs: dict[str, str], scheme: str
    ) -> list[dict[str, str]]:
        """Return list of security header finding dicts."""
        issues: list[dict[str, str]] = []
        hdrs_lower = {k.lower(): v for k, v in hdrs.items()}

        for hdr, meta in _SECURITY_HEADERS.items():
            if hdr not in hdrs_lower:
                # HSTS only applies to HTTPS
                if hdr == "strict-transport-security" and scheme != "https":
                    continue
                issues.append({
                    "header":   hdr,
                    "severity": meta["severity"],
                    "issue":    meta["miss"],
                    "fix":      meta["fix"],
                })

        # Check for version disclosure in existing headers
        for hdr in ("server", "x-powered-by", "x-aspnet-version",
                    "x-aspnetmvc-version", "x-generator"):
            val = hdrs_lower.get(hdr, "")
            if val:
                # Check if version number present
                if re.search(r"\d+\.\d+", val):
                    issues.append({
                        "header":   hdr,
                        "severity": "LOW",
                        "issue":    f"Version disclosed: {hdr}: {val}",
                        "fix":      f"Remove or sanitize the {hdr} header",
                    })

        # HSTS strength check
        hsts = hdrs_lower.get("strict-transport-security", "")
        if hsts:
            age_m = re.search(r"max-age=(\d+)", hsts)
            if age_m and int(age_m.group(1)) < 15552000:  # < 180 days
                issues.append({
                    "header":   "strict-transport-security",
                    "severity": "LOW",
                    "issue":    f"HSTS max-age too short ({age_m.group(1)}s); recommend ≥ 15552000",
                    "fix":      "Strict-Transport-Security: max-age=31536000; includeSubDomains",
                })

        # CSP strength
        csp = hdrs_lower.get("content-security-policy", "")
        if csp and ("unsafe-inline" in csp or "unsafe-eval" in csp):
            issues.append({
                "header":   "content-security-policy",
                "severity": "MEDIUM",
                "issue":    "CSP contains 'unsafe-inline' or 'unsafe-eval' — XSS mitigation weakened",
                "fix":      "Remove unsafe-inline/unsafe-eval from CSP",
            })

        return issues

    # ── Cookie analysis ───────────────────────────────────────────────────────

    def analyze_cookies(self, hdrs: dict[str, str]) -> list[dict[str, Any]]:
        """Return list of cookie security findings."""
        results: list[dict[str, Any]] = []
        hdrs_lower = {k.lower(): v for k, v in hdrs.items()}
        raw = hdrs_lower.get("set-cookie", "")
        if not raw:
            return results

        # Multiple cookies may be in multiple Set-Cookie headers
        # http.client merges them with comma in some cases; split on '; ' boundaries
        for ck_hdr in re.split(r",\s*(?=[A-Za-z])", raw):
            parts = [p.strip() for p in ck_hdr.split(";")]
            if not parts:
                continue
            name_val = parts[0]
            name = name_val.split("=")[0].strip()
            flags = {p.strip().lower() for p in parts[1:]}
            issues = []
            if "httponly" not in flags:
                issues.append("missing HttpOnly")
            if "secure" not in flags and self.scheme == "https":
                issues.append("missing Secure flag")
            samesite = next((f for f in flags if f.startswith("samesite")), "")
            if not samesite:
                issues.append("missing SameSite")
            elif "samesite=none" in samesite and "secure" not in flags:
                issues.append("SameSite=None without Secure")
            results.append({
                "name":   name,
                "flags":  list(flags),
                "issues": issues,
            })
        return results

    # ── Path discovery ────────────────────────────────────────────────────────

    def discover_paths(
        self, threads: int = 20
    ) -> list[dict[str, Any]]:
        """Check sensitive paths concurrently. Returns list of found paths."""
        found: list[dict[str, Any]] = []
        lock = threading.Lock()

        def _check(path: str, description: str):
            code, hdrs, body = self._get(path, follow_redirects=0)
            if code in (200, 201, 204, 301, 302, 307, 401, 403):
                severity = "HIGH" if any(
                    kw in description for kw in ("HIGH", "secret", "config", "dump", "phpinfo")
                ) else ("MEDIUM" if code in (200, 201, 204) else "LOW")
                with lock:
                    found.append({
                        "path":        path,
                        "description": description,
                        "status":      code,
                        "severity":    severity,
                        "size":        len(body),
                    })

        with ThreadPoolExecutor(max_workers=threads) as pool:
            futs = {pool.submit(_check, p, d): (p, d) for p, d in _SENSITIVE_PATHS}
            for fut in as_completed(futs):
                try:
                    fut.result()
                except Exception:
                    pass

        return sorted(found, key=lambda x: (x["status"], x["path"]))

    # ── HTTP method enumeration ───────────────────────────────────────────────

    def enumerate_methods(self) -> list[str]:
        """Return list of allowed HTTP methods."""
        allowed: list[str] = []

        # First try OPTIONS
        code, hdrs, _ = self._get("/", method="OPTIONS", follow_redirects=0)
        allow_hdr = hdrs.get("allow", "") or hdrs.get("access-control-allow-methods", "")
        if allow_hdr:
            return [m.strip().upper() for m in allow_hdr.split(",") if m.strip()]

        # Probe each method
        for method in ("PUT", "DELETE", "TRACE", "PATCH"):
            try:
                code2, _, _ = self._get("/", method=method, follow_redirects=0)
                if code2 not in (405, 501, 0):
                    allowed.append(method)
            except Exception:
                pass

        if "TRACE" in allowed:
            _log.warning("TRACE method allowed on %s — XST risk", self.target)
        return allowed

    # ── robots.txt / sitemap ──────────────────────────────────────────────────

    def parse_robots(self) -> list[str]:
        """Return list of Disallow/Allow entries from robots.txt."""
        code, _, body = self._get("/robots.txt", follow_redirects=1)
        if code != 200 or not body:
            return []
        entries: list[str] = []
        for line in body.splitlines():
            line = line.strip()
            if line.lower().startswith(("disallow:", "allow:", "sitemap:")):
                entries.append(line)
        return entries

    def parse_sitemap(self) -> list[str]:
        """Return URLs from sitemap.xml (top 50)."""
        code, _, body = self._get("/sitemap.xml", follow_redirects=1)
        if code != 200 or not body:
            return []
        return re.findall(r"<loc>(.*?)</loc>", body, re.IGNORECASE)[:50]

    # ── Redirect chain ────────────────────────────────────────────────────────

    def follow_redirects(self) -> list[str]:
        """Return the full redirect chain from /."""
        self._results.redirect_chain.clear()
        self._get("/", follow_redirects=5)
        return list(self._results.redirect_chain)

    # ── Full probe ────────────────────────────────────────────────────────────

    def probe_all(self, path_discovery: bool = True) -> WebFingerprint:
        """
        Run all fingerprinting checks and return a WebFingerprint.

        Args:
            path_discovery: Whether to run the sensitive path scan (slower).
        """
        _log.info("HTTP probe: %s://%s:%d", self.scheme, self.target, self.port)

        # ── Base request ──────────────────────────────────────────────────────
        code, hdrs, body = self._get("/")
        if code == 0:
            _log.error("No HTTP response from %s:%d", self.target, self.port)
            return self._results

        self._results.status_code = code
        self._results.all_headers = dict(hdrs)
        self._results.server = hdrs.get("server", "")

        cookies_str = hdrs.get("set-cookie", "")

        # ── WAF / CDN ──────────────────────────────────────────────────────────
        self._results.waf = self.detect_waf(code, hdrs, body, cookies_str)
        self._results.cdn = self.detect_cdn(hdrs)
        if self._results.waf:
            _log.info("[bold yellow]WAF detected[/]: %s", self._results.waf)
        if self._results.cdn:
            _log.info("[bold cyan]CDN detected[/]: %s", self._results.cdn)

        # ── Technology stack ───────────────────────────────────────────────────
        self._results.technologies = self.fingerprint_tech(hdrs, body, cookies_str)
        if self._results.technologies:
            _log.info("Technologies: %s", ", ".join(self._results.technologies))

        # ── Security headers ───────────────────────────────────────────────────
        self._results.security_header_issues = self.audit_security_headers(
            hdrs, self.scheme
        )

        # ── Cookie analysis ────────────────────────────────────────────────────
        self._results.cookies = self.analyze_cookies(hdrs)

        # ── Version disclosures ────────────────────────────────────────────────
        for hdr in ("server", "x-powered-by", "x-aspnet-version",
                    "x-generator", "x-drupal-cache"):
            val = hdrs.get(hdr, "")
            if val:
                self._results.version_disclosures.append(f"{hdr}: {val}")

        # ── robots.txt ────────────────────────────────────────────────────────
        self._results.robots_entries = self.parse_robots()

        # ── HTTP methods ──────────────────────────────────────────────────────
        self._results.allowed_methods = self.enumerate_methods()

        # ── Redirect chain ────────────────────────────────────────────────────
        self._results.redirect_chain = self.follow_redirects()

        # ── Path discovery ─────────────────────────────────────────────────────
        if path_discovery:
            _log.info("Scanning %d sensitive paths on %s …",
                      len(_SENSITIVE_PATHS), self.target)
            self._results.interesting_paths = self.discover_paths()
            found_count = len(self._results.interesting_paths)
            if found_count:
                _log.info("[bold green]%d interesting path(s) found[/]", found_count)

        return self._results

    def print_results(self, fp: WebFingerprint | None = None) -> None:
        """Print formatted results to the console."""
        from recon.core.logger import console
        from rich.table import Table
        from rich import box

        fp = fp or self._results

        console.print(f"\n[bold cyan]HTTP Fingerprint:[/] {fp.scheme}://{fp.target}:{fp.port}")
        console.print(f"  Status:      [bold]{fp.status_code}[/]")
        console.print(f"  Server:      [yellow]{fp.server or '(none)'}[/]")
        console.print(f"  WAF:         [bold {'red' if fp.waf else 'green'}]{fp.waf or 'None detected'}[/]")
        console.print(f"  CDN:         [cyan]{fp.cdn or 'None detected'}[/]")

        if fp.technologies:
            console.print(f"  Tech stack:  [green]{', '.join(fp.technologies)}[/]")

        if fp.version_disclosures:
            console.print("\n[bold yellow]Version Disclosures:[/]")
            for v in fp.version_disclosures:
                console.print(f"  [yellow]{v}[/]")

        if fp.security_header_issues:
            t = Table("Severity", "Header", "Issue", box=box.SIMPLE)
            sev_color = {"HIGH": "red", "MEDIUM": "yellow",
                         "LOW": "cyan", "INFO": "dim"}
            for issue in fp.security_header_issues:
                sev = issue["severity"]
                t.add_row(
                    f"[{sev_color.get(sev,'white')}]{sev}[/]",
                    issue["header"],
                    issue["issue"],
                )
            console.print("\n[bold]Security Header Issues:[/]")
            console.print(t)

        if fp.interesting_paths:
            t2 = Table("Status", "Severity", "Path", "Description", box=box.SIMPLE)
            for p in fp.interesting_paths:
                sev = p["severity"]
                col = "red" if sev == "HIGH" else ("yellow" if sev == "MEDIUM" else "cyan")
                t2.add_row(
                    str(p["status"]),
                    f"[{col}]{sev}[/]",
                    p["path"],
                    p["description"],
                )
            console.print("\n[bold]Interesting Paths Found:[/]")
            console.print(t2)

        if fp.allowed_methods:
            dangerous = {"TRACE", "PUT", "DELETE"}
            method_strs = [
                f"[bold red]{m}[/]" if m in dangerous else m
                for m in fp.allowed_methods
            ]
            console.print(f"\n  Allowed methods: {', '.join(method_strs)}")

        if fp.robots_entries:
            console.print(f"\n  robots.txt ({len(fp.robots_entries)} entries)")
